### ISSUE TITLE
Implement `pin_upload()` and `pin_download()`

### ISSUE THREAD

**Issue by juliasilge** [rstudio/pins-python#161] opened 2022-10-27 16:55 UTC
These functions ([docs for R](https://pins.rstudio.com/dev/reference/pin_download.html)) let folks publish and share data that can't be stored as a Python object, or that folks may want to store in a custom way. For example, it allows [storing via a user-specified format](https://pins.rstudio.com/dev/articles/managing-custom-formats.html).

**Comment by machow** [comment] 2022-11-01 15:07
It looks like this is a duplicate of https://github.com/rstudio/pins-python/issues/161 . I'm going to close here, so we can track in one place

**Closed by machow** 2022-11-01 15:07 UTC
