### ISSUE TITLE
Implement unversioned pins

### ISSUE THREAD

**Issue by juliasilge** [rstudio/pins-python#162] opened 2022-10-27 16:58 UTC
In some situations, folks want to store and publish a pin, but not version it. This is typically because it is a very large object where the versions take a lot of space on disk, or I have seen folks do this when they are storage-limited on their server.

**Comment by machow** [comment] 2022-11-01 15:08
This looks like a duplicate of https://github.com/rstudio/pins-python/issues/31. I'm going to close here so we can track in one place

**Closed by machow** 2022-11-01 15:08 UTC
